name: ESP32 builder IDF_Arduino 4.4.3

on:
  workflow_dispatch:  # Manually start a workflow
#  push:
#    branches: master
#    paths-ignore:
#    - '.github/**' # Ignore changes towards the .github directory

jobs:
  build-libs:
    name: Build Arduino Libs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: bash ./tools/prepare-ci.sh
    - name: Build Arduino Libs
      run: bash ./build.sh
    - name: Release
      uses: jason2866/action-gh-release@v1.2
      #if: startsWith(github.ref, 'refs/tags/')
      with:
        tag_name: ${{ github.run_number }}
        prerelease: true
        files: dist/framework*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
